apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci2
  labels:
    app: ci2
    hail.is/sha: "{{ pr.sha }}"
spec:
  selector:
    matchLabels:
      app: ci2
  replicas: 1
  template:
    metadata:
      labels:
        app: ci2
        hail.is/sha: "{{ pr.sha }}"
    spec:
      containers:
        - name: ci2
          image: {{ ci2_image.image }}
          env:
            - name: CI2_OAUTH_TOKEN
              value: /secrets/oauth-token/oauth-token
            - name: WATCHED_BRANCHES
              value: '["hail-is/hail:master", "hail-is/hail:0.1", "Nealelab/cloudtools:master"]'
            - name: BATCH_SERVER_URL
              value: http://batch.default
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /secrets/oauth-token
              readOnly: true
              name: hail-ci-0-1-github-oauth-token
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: hail-ci-0-1-github-oauth-token
          secret:
            secretName: hail-ci-0-1-github-oauth-token
---
apiVersion: v1
kind: Service
metadata:
  name: ci2
  labels:
    app: ci2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ci2
