#!/usr/bash

echo 'starting Container cluster seqr-backend-solr-ingest'
gcloud container --project "seqr-project" clusters create "seqr-backend-solr-ingest" --zone "us-central1-a" --machine-type "n1-standard-8" --image-type "COS" --disk-size "100" --scopes "https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring.write","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --num-nodes "1" --network "default" --enable-cloud-logging --enable-cloud-monitoring

gcloud --project seqr-project container clusters get-credentials --zone us-central1-a seqr-backend-solr-ingest

echo 'starting Dataproc cluster seqr-backend-export-cluster'
gcloud dataproc clusters create seqr-backend-solr-ingest --zone us-central1-a --master-machine-type n1-standard-8 --master-boot-disk-size 100 --num-workers 2 --worker-machine-type n1-standard-8 --worker-boot-disk-size 100 --num-preemptible-workers 2 --image-version 1.1 --project seqr-project --initialization-actions 'gs://hail-common/hail-init.sh'

kubectl create \
	-f ../../kubernetes/configs/solr-ingest.yaml \
	-f ../../kubernetes/configs/solr-service.yaml

# FIXME wait for Running
