#!/bin/bash

set -ex

kubectl delete \
	-f ../../kubernetes/configs/solr-ingest.yaml \
	-f ../../kubernetes/configs/solr-service.yaml

gcloud -q --project seqr-project container clusters delete --zone us-central1-a seqr-backend-solr-ingest

gcloud -q --project seqr-project dataproc clusters delete --zone us-central1-a seqr-backend-solr-ingest
