FROM {{ base_image.image }}

COPY setup.py /batch/
COPY batch/ /batch/batch/
RUN pip3 install --no-cache-dir /batch && \
  rm -rf /batch

COPY test/ /test/

CMD ["python3", "-m", "unittest", "-v", "/test/test_batch.py"]
