apiVersion: v1
kind: Pod
metadata:
  name: test-batch
spec:
  containers:
  - name: test-batch
    image: "{{ test_batch_image.image }}"
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  restartPolicy: Never
