apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: site-deployment
  labels:
    app: site
    hail.is/sha: "{{ pr.sha }}"
spec:
  selector:
    matchLabels:
      app: site
  replicas: 1
  template:
    metadata:
      labels:
        app: site
        hail.is/sha: "{{ pr.sha }}"
    spec:
      containers:
      - name: site
        image: "{{ site_image.image }}"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
