kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cassandra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      volumes:
      - name: cassandra-data
        gcePersistentDisk:
          # This disk must already exist.
          pdName: cassandra-data
          fsType: ext4
      containers:
      - name: cassandra-pod
        image: cassandra:3.9
        ports:
        - containerPort: 9042
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        resources:
          requests:
            cpu: 200m
      securityContext:
        fsGroup: 999
      restartPolicy: Always
      dnsPolicy: ClusterFirst
