kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: solr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: solr
    spec:
      volumes:
      - name: solr-data
        gcePersistentDisk:
          # This disk must already exist.
          pdName: solr-data
          fsType: ext4
      containers:
      - name: solr-pod
        image: gcr.io/seqr-project/solr
        ports:
        - containerPort: 30002
          protocol: TCP
        - containerPort: 31002
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: SOLR_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SOLR_PORT
          value: "30002"
        volumeMounts:
        - name: solr-data
          mountPath: /solr-data
        resources:
          requests:
            memory: "28G"
            cpu: "7"
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      dnsPolicy: ClusterFirst
