apiVersion: v1
kind: ServiceAccount
metadata:
  name: letsencrypt
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: update-letsencrypt-config
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["letsencrypt-config"]
  verbs: ["get", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: letsencrypt-update-letsencrypt-config
subjects:
- kind: ServiceAccount
  name: letsencrypt
  namespace: default
roleRef:
  kind: Role
  name: update-letsencrypt-config
  apiGroup: ""
